---
ryezone_labs_provision_user: vagrant
ansible_ssh_user: vagrant
ansible_ssh_pass: vagrant

hosts_hostname: "{{ ansible_hostname }}"
ansible_ssh_private_key_file: /opt/.ssh/id_rsa
ryezone_labs_public_key_path: /opt/.ssh/id_rsa.pub

ryezone_labs_external_dns:
  - 1.1.1.1
  - 1.0.0.1
ryezone_labs_wanInterface: eth0
ryezone_labs_lanInterface: eth1
ryezone_labs_lanAddress: 10.100.10.1
ryezone_labs_dcAddress:  10.100.10.2
ryezone_labs_managerAddress: 10.100.10.3
ryezone_labs_workerAddress: 10.100.10.4
ryezone_labs_lanNetwork: 10.100.10.0
ryezone_labs_lanNetmask: 255.255.255.0
ryezone_labs_lanBroadcast: 10.100.10.255
ryezone_labs_lanDhcpRangeStart: 10.100.10.100
ryezone_labs_lanDhcpRangeEnd: 10.100.10.250
ryezone_labs_domain_suffix: local
ryezone_labs_domain_organization: domain
ryezone_labs_domain_controller_hostname: dc
ryezone_labs_top_level_domain: "{{ ryezone_labs_domain_organization }}.{{ ryezone_labs_domain_suffix }}"
packer_init_desktop: false

docker_compose_version: 1.23.1
docker_compose_checksum: "sha256:c176543737b8aea762022245f0f4d58781d3cb1b072bc14f3f8e5bb96f90f1a2"
docker_version: 5:18.09.4~3-0~ubuntu-bionic
docker_ubuntu_version: bionic
docker_release_type: stable

ntp_enabled: True
ntp_timezone: Etc/UTC
ntp_manage_config: True
ntp_area: us
ntp_servers: 
  - "{{ ryezone_labs_lanAddress }}"

netplan_enabled: true
netplan_config_file:      /etc/netplan/config.yaml
netplan_remove_existing:  true
netplan_configuration:
  network:
    version: 2
    renderer: networkd
    ethernets:
      eth0:
        dhcp4: true
        dhcp6: false
        optional: true
        nameservers:
          addresses:
            - 10.100.10.1
            - 1.1.1.1

systemd_resolved:
  disabled: true
  nameservers:
    - 10.100.10.1
    - 1.1.1.1
  search_zones:
    - "{{ ryezone_labs_top_level_domain }}"