---
# defaults file for ansible-netplan
netplan_config_file:      /etc/netplan/config.yaml
netplan_remove_existing:  true
netplan_configuration:
  network:
    version: 2
    renderer: networkd
    ethernets:
      eth0:
        dhcp4: true
        dhcp6: false
        optional: true
        nameservers:
          addresses: "{{ ryezone_labs_external_dns }}"
      eth1:
        dhcp4: false
        dhcp6: false
        addresses:
          - "{{ ryezone_labs_lanAddress }}/24"
        optional: true
        nameservers:
          addresses:
            - 127.0.0.1
          search:
            - "{{ ryezone_labs_top_level_domain }}"

dhcp_hosts:
  - name: router
    mac_address: 00:35:10:00:00:01
    fixed_address: "{{ ryezone_labs_lanAddress }}"
  - name: dc
    mac_address: 00:35:10:00:00:02
    fixed_address: "{{ ryezone_labs_dcAddress }}"
  - name: manager
    mac_address: 00:35:10:00:00:03
    fixed_address: "{{ ryezone_labs_managerAddress }}"
  - name: worker
    mac_address: 00:35:10:00:00:04
    fixed_address: "{{ ryezone_labs_workerAddress }}"

edge_firewall_open_incoming_tcp_ports:
  - cidr: 172.16.0.0/12
    port: 22

edge_firewall_allowed_incoming_icmp:
  - icmp_type: 8
    cidr: 172.16.0.0/12

edge_firewall_closed_incoming_udp_ports:
  - cidr: 172.16.0.0/12
    port: 33434:33523

edge_firewall_nat_rules:
  - protocol: tcp
    wan_interface: "{{ ryezone_labs_wanInterface }}"
    wan_port: 80
    lan_interface: "{{ ryezone_labs_lanInterface }}"
    lan_address: "{{ ryezone_labs_lanAddress }}"
    host_port: 80
    host_address: 10.100.10.11
