---
- hosts: 127.0.0.1
  connection: local
  roles:
    - ryezone_labs.hosts

- hosts: acs
  roles:
    - ryezone_labs.ansible_control_server

- hosts: all
  roles:
    - ryezone_labs.ssh
    - ryezone_labs.packer_init
    - ryezone_labs.ntp
    - ryezone_labs.trusted_certificates

- hosts: gateway
  roles:
    - mrlesmithjr.netplan
    - ryezone_labs.dhcp
    - ryezone_labs.edge_firewall
  become: yes

- hosts: dns
  roles:
    - ryezone_labs.dns

- hosts: docker
  roles:
    - ryezone_labs.docker

- hosts: all
  roles:
    - ryezone_labs.packer_complete